artcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

my_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name="about"),
    path('accounts/signup/', views.signup, name="signup"),
    path('art/', views.art_index, name="art-index"),
    path('art/<int:art_id>/', views.art_detail, name="art-detail"),
    path('art/create/', views.ArtCreate.as_view(), name='art-create'),
    path('art/<int:pk>/update', views.ArtUpdate.as_view(), name='art-update'),
    path('art/<int:pk>/delete/', views.ArtDelete.as_view(), name="art-delete"),
    path('art/<int:art_id>/add-copy/', views.add_copy, name="add-copy"),
    path('list/create', views.ListCreate.as_view(), name='list-create'),
    path('list/<int:pk>/', views.ListDetail.as_view(), name='list-detail'),
    path('list/', views.ListList.as_view(), name='list-index'),
    path('list/<int:pk>/update', views.ListUpdate.as_view(), name='list-update'),
    path('list/<int:pk>/delete/', views.ListDelete.as_view(), name='list-delete'),
    path('art/<int:art_id>/associate-list/<int:list_id>/', views.associate_list, name='associate-list'),
    path('art/<int:art_id>/remove-list/<int:list_id>/', views.remove_list, name='remove-list'),
]

my_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

medium_choices = (
    ('oil', 'Oil Paint'),
    ('acrylic', 'Acrylic Paint'),
    ('watercolor', 'Watercolor'),
    ('gouache', 'Gouache'),
    ('pastels', 'Pastels'),
    ('ink', 'Ink'),
    ('graphite', 'Graphite/Charcoal'),
    ('color_pencils', 'Colored Pencils'),
    ('mixed_media', 'Mixed Media'),
    ('other', 'Other'),
)
    
movement_choices = (
    ('abstract', 'Abstract Expressionism'),
    ('art_deco', 'Art Deco'),
    ('art_nouveau', 'Art Nouveau'),
    ('baroque', 'Baroque'),
    ('classicism', 'Classicism'),
    ('contemporary', 'Contemporary Art'),
    ('cubism','Cubism'),
    ('expressionism', 'Expressionism'),
    ('realism', 'Hyperrealism'),
    ('renaissance', 'Renaissance'),
    ('impressionism', 'Impressionism'),
    ('modern', 'Modern Art'),
    ('neoclassicism', 'Neoclassicism'),
    ('pop', 'Pop Art'),
    ('rococo', 'Rococo'),
    ('surrealism', 'Surrealism'),
)
color_choices = (
    ('aliceBlue', 'Alice Blue'),
    ('aquamarine', 'Aquamarine'),
    ('chartreuse', 'Chartreuse'),
    ('coral', 'Coral'),
    ('crimson', 'Crimson'),
    ('seaGree', 'Dark Sea Green'),
    ('deepPink','Deep Pink'),
    ('dodgerBlue', 'Dodger Blue'),
    ('slateGray', 'Slate Gray'),
    ('tomato', 'Tomato'),
)
# Create your models here.
class List(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20, choices=color_choices)
    notes = models.CharField(max_length=150)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("list-detail", kwargs={"pk": self.id})
    
class Art(models.Model):
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    date = models.CharField('Year Completed', max_length=50)
    medium = models.CharField(max_length=100, choices=medium_choices)
    movement = models.CharField(max_length=100, choices=movement_choices, blank=True, null=True)
    location = models.CharField(max_length=200, default="unknown")
    viewed = models.BooleanField("Viewed in Person", default=False)
    image = models.URLField(max_length=200)
    # Add the M:M relationship
    lists = models.ManyToManyField(List)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
    
    # Define a method to get the URL for this particular instance
    def get_absolute_url(self):
        # Use the 'reverse' function to dynamically find the URL for viewing this models's details
        return reverse("art-detail", kwargs={'art_id': self.id})
    
    
class Copy(models.Model):
    art = models.ForeignKey(Art, on_delete=models.CASCADE)
    artist = models.CharField(max_length=100)
    date = models.DateField('Date Painted')
    notes = models.CharField(max_length=150)
    image = models.URLField(max_length=200)
    
    def __str__(self):
        return f"{self.artist} painted on {self.date}"
    
    class Meta:
        ordering = ['-date']
        # "-" newest dates with appear first

my_app/forms.py
from django import forms
from .models import Copy

class CopyForm(forms.ModelForm):
    class Meta:
        model = Copy
        fields = ['artist', 'date', 'notes', 'image']
        widgets = {
            'date' : forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type' : 'date'
                }
            ),
        }

my_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Art, List, Copy
from .forms import CopyForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# from django.http import HttpResponse

# class Art:
#     def __init__(self, title, artist, date, medium, movement, image):
#         self.title = title
#         self.artist = artist
#         self.date = date
#         self.medium = medium
#         self.movement = movement
#         self.image = image

# art = [
#     Art('Sunrise', 'Claude Monet', 1872, "Oil", "Impression", "https://www.claude-monet.com/assets/img/paintings/impression-sunrise.jpg"),
#     Art('Sunrise', 'Claude Monet', 1872, "Oil", "Impression" , "https://www.claude-monet.com/assets/img/paintings/impression-sunrise.jpg"),
#     Art('Sunrise', 'Claude Monet', 1872, "Oil", "Impression", "https://www.claude-monet.com/assets/img/paintings/impression-sunrise.jpg"),
#     Art('Sunrise', 'Claude Monet', 1872, "Oil", "Impression", "https://www.claude-monet.com/assets/img/paintings/impression-sunrise.jpg")
# ]

# Create your views here.
# def home(request):
#     return render(request, 'home.html')
class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def art_index(request):
    # art = Art.objects.all()
    art = Art.objects.filter(user=request.user)
    # art = request.user.art_set.all()
    return render(request, 'art/index.html', {'art' : art})

@login_required
def art_detail(request, art_id):
    art = Art.objects.get(id=art_id)
    # fetch all lists
    # lists = List.objects.all()
    # only get the lists the artwork has not been assigned to
    lists_art_is_not_on = List.objects.exclude(id__in = art.lists.all().values_list('id'))
    copy_form = CopyForm()
    return render(request, 'art/detail.html', {
                'art' : art,
                'copy_form' : copy_form,
                'lists' : lists_art_is_not_on,
                })

@login_required
def add_copy(request, art_id):
    # create a ModelForm instance using the data in request.POST
    form = CopyForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the art_id assigned
        new_copy = form.save(commit=False)
        new_copy.art_id = art_id
        new_copy.save()
    return redirect('art-detail', art_id = art_id)

@login_required
def associate_list(request, art_id, list_id):
    Art.objects.get(id=art_id).lists.add(list_id)
    return redirect('art-detail', art_id=art_id)

@login_required
def remove_list(request, art_id, list_id):
    Art.objects.get(id=art_id).lists.remove(list_id)
    return redirect('art-detail', art_id=art_id)

class ArtCreate(LoginRequiredMixin, CreateView):
    model = Art
    fields = ['title', 'artist', 'date', 'medium', 'movement', 'location', 'viewed', 'image']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ArtUpdate(LoginRequiredMixin, UpdateView):
    model = Art
    fields = ['title', 'artist', 'date', 'medium', 'movement', 'location', 'viewed', 'image']

class ArtDelete(LoginRequiredMixin, DeleteView):
    model = Art
    success_url = '/art/'
    
class ListCreate(LoginRequiredMixin, CreateView):
    model = List
    fields = '__all__'
    
class ListList(LoginRequiredMixin, ListView):
    model = List
    
class ListDetail(LoginRequiredMixin, DetailView):
    model = List
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['arts'] = self.object.art_set.all()
        return context
        

class ListUpdate(LoginRequiredMixin, UpdateView):
    model = List
    fields = '__all__'
    
class ListDelete(LoginRequiredMixin, DeleteView):
    model = List
    success_url = '/list/'
    
    
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('art-index')
        else:
            error_message = 'Invalid sign up - try again'
    # else - Get request, render signup.html
    form = UserCreationForm()
    return render(request, 'signup.html', {
        'form' : form,
        'error_message' : error_message,
    })

my_app/templates/art/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static "css/art/art-detail.css" %}" />
{% endblock head %}

{% block content %}
<section class="cat-container">
    <div class="cat-img">
        <img src="{{art.image}}" alt="thumbnail art image">
    </div>
    <div class="cat-details">
        <h1>{{art.title}}</h1>
        <h2>{{art.artist}}</h2>
        <p>Completed: {{art.date}}</p>
        <p>Medium: {{art.medium}}</p>
        <p>Movement: {{art.movement}}</p>
        <p>Location: {{art.location}}</p>
        {% if art.viewed %}
            <p>Viewed in Person: &#9745;</p>
        {% endif %}

        <div class="cat-actions">
            <a href="{% url "art-update" art.id %}" class="btn warn">Edit</a>
            <a href="{% url "art-delete" art.id %}" class="btn danger">Delete</a>
        </div>
    </div>
</section>

<div class="feeding-toy-container">
    <section class="feedings">
        <div class="subsection-title">
            <h2>Master Copies</h2>
        </div>
        <h3>Add A Master Copy</h3>
        <form
            action="{%url 'add-copy' art.id%}"
            method="post" 
            class="subsection-content" 
            autocomplete="off"
            >
            {% csrf_token %}
            {{copy_form.as_p}}
            <button type="submit" class="btn submit">Add</button>
        </form>

        <h3>Other Master Copies</h3>
        {% if art.copy_set.all.count %}

            {% for copy in art.copy_set.all %}
            <div class="card">
                <div class="card-content">
                    <div class="cat-img">
                        <img src="{{copy.image}}" alt="thumbnail art image">
                    </div>
                    <div class="cat-details">
                        <h2>{{copy.artist}}</h2>
                        <p>{{copy.date}}</p>
                        <p>{{copy.notes}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="subsection-content">
                <p>⚠️ Add a new Master Copy</p>
            </div>
        {% endif %}
        
    </section>

    <section class="toys">
        <div class="subsection-title">
            <h2>Lists</h2>
        </div>

        <h3></h3>
        <div class="subsection-content">
            {% if art.lists.count %}
                {% for list in art.lists.all %}
                <div class="toy-container">
                    <div class="color-block" style="background-color: {{list.color}}"></div>
                    <a href="{% url "list-detail" list.id %}">
                        <p>{{list.name}} : {{list.notes}}</p>
                    </a>
                    <form action="{% url "remove-list" art.id list.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Remove from List</button>
                    </form>
                </div>
                {% endfor %}
            {% else %}
            <p class="no-toys">{{art.title}} - has not been assigned to a List</p>
            {% endif %}
        </div>
        
        <h3>Available Lists</h3>
        <div class="subsection-content">
            {% if lists.count %}
                {% for list in lists.all %}
                    <div class="toy-container">
                        <div class="color-block" style="background-color: {{list.color}}"></div>
                        <a href="{% url "list-detail" list.id %}">
                            <p>{{list.name}}</p>
                        </a>
                        <form action="{% url "associate-list" art.id list.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn submit">Add to List</button>
                        </form>
                    </div>
                {% endfor %}
            {% else %}
                    <p class="all-toys">{{art.title}} is on all the available lists</p>
            {% endif %}
        </div>
    </section>
</div>

{% endblock content %}

my_app/templates/art/index.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static "css/art/art-index.css" %}">
{% endblock head %}

{% block content %}
<section class="page-header">
    <h1>Art Gallery</h1>
</section>

<section class="card-container">
    {% for art in art %}
    
    <div class="card">
        <a href="{% url "art-detail" art.id %}">
            <div class="card-content">
                <div class="card-img-container">
                    <img src="{{art.image}}" alt="thumbnail art image">
                </div>
                <h2 class="card-title">{{art.title}}</h2>
                <h4>{{art.artist}}</h4>
                {% if art.viewed %}
                <p>&#9745;</p>
                {% endif %}
            </div>
        </a>
    </div>
    
    {% endfor %}
</section>

{% endblock content %}